# Generated by Django 6.0 on 2026-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medoc',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
