# Generated by Django 6.0 on 2026-01-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicaments', '0003_panier_lignepanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='medoc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
